name: Java CI with Maven

on:
  push:
    branches: [ "QA_branch" ]
  pull_request:
    branches: [ "QA_branch" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install missing dependencies (for Playwright)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev libgraphene-1.0-0 libwoff1 \
            libvpx-dev libevent-dev libopus-dev libgstreamer1.0-0 \
            libgstreamer-plugins-base1.0-dev libflite1 libavif-dev \
            libharfbuzz-dev libsecret-1-dev libhyphen-dev libmanette-0.2-dev \
            libgles2-mesa-dev x264

      - name: Build with Maven
        run: mvn clean test -DwhichRunner=TestRunner -DwhichBrowser=chrome
